

module.exports = {
  clone: require('./clone/index.js').default,
  compress: require('./compress/index.js').default,
  curry: require('./curry/index.js').default,
  deepClone: require('./deepClone/index.js').default,
  empty: require('./empty/index.js').default,
  extend: require('./extend/index.js').default,
  find: require('./find/index.js').default,
  first: require('./first/index.js').default,
  flatten: require('./flatten/index.js').default,
  fuzzySearch: require('./fuzzySearch/index.js').default,
  has: require('./has/index.js').default,
  identical: require('./identical/index.js').default,
  isArray: require('./isArray/index.js').default,
  isEmpty: require('./isEmpty/index.js').default,
  isEqual: require('./isEqual/index.js').default,
  isFunction: require('./isFunction/index.js').default,
  isNull: require('./isNull/index.js').default,
  isNumber: require('./isNumber/index.js').default,
  isObject: require('./isObject/index.js').default,
  isRegExp: require('./isRegExp/index.js').default,
  isString: require('./isString/index.js').default,
  last: require('./last/index.js').default,
  mean: require('./mean/index.js').default,
  not: require('./not/index.js').default,
  nth: require('./nth/index.js').default,
  omit: require('./omit/index.js').default,
  range: require('./range/index.js').default,
  removeAtIndex: require('./removeAtIndex/index.js').default,
  replaceAtIndex: require('./replaceAtIndex/index.js').default,
  type: require('./type/index.js').default
};
